### ISSUE TITLE
pls update cocoaPods for swift 3

### ISSUE THREAD

**Issue by conscientiousness** [LeoMobileDeveloper/PullToRefreshKit#1]
请问大神pod没更新么？谢谢

**Comment by LeoMobileDeveloper** [comment]
@conscientiousness  CocoaPod源没更新，上面的应该还是Swift 2.3的版本，着急的话可以先把源代码拷贝进去。不急的话，我周末会更新CocoaPod

**Comment by LeoMobileDeveloper** [comment]
已更新Swift 3.0 CocoaPod源 @conscientiousness
