### ISSUE TITLE
在 iOS 11 使用 ElasticRefreshHeader, 刷新状态不正确

### ISSUE THREAD

**Issue by Joe0708** [LeoMobileDeveloper/PullToRefreshKit#20]
在 iOS 11 使用 ElasticRefreshHeader 动画组件, 刷新状态不正确， 下拉一直在 pulling 状态，刷新完成也是 

如图不管下拉还是松开都是这样：
![B9498AD6-40B1-4886-A263-8403E4772669.png](https://i.loli.net/2017/11/07/5a019513eafad.png)

**Comment by LeoMobileDeveloper** [comment]
试试

```
  if #available(iOS 11.0, *) {
            UITableView.appearance().contentInsetAdjustmentBehavior = .never
    }
```

**Comment by Joe0708** [comment]
更新 0.8.0 之后解决了这个问题, 但是我发现带来了更多的问题
自定义的 Footer ,之前不需要设置 FooterView的高度, 只需返回 heightForRefreshingState 即可,
而现在貌似必须要设置高度, 文档没有注明修改日志., 而且 heightForRefreshingState 方法并不会调用
设置 Footer View 高度后, 内容显示在屏幕的底部右侧, 并不是居中的(Frame 有设置), 使用默认的 Footer 也有同样的问题,  但是使用提供的 Demo 并没有这个问题, 我不知道为什么, 但这让我不得不用回 0.7.0 版本, 希望能解决, 感谢

**Comment by Joe0708** [comment]
ElasticRefreshHeader 刷新状态这个问题在真机上还是有, 模拟器上没问题 😭

**Comment by LeoMobileDeveloper** [comment]
@Joe0708 谢谢这么详细的反馈，v0.8.0主要的目的是重新定义老的API接口，改的有些仓促。因该是改出了一些问题，会在v0.8.2中修复你说的这些问题

**Comment by LeoMobileDeveloper** [comment]
试试V0.8.2，应该修复了footer的位置问题，并且添加了一个自定义footer的Demo：NeteaseNewsFooter。另外，我在同事的iPhoneX上运行0.8.2的Demo，ElasticRefreshHeader可以正常工作了。

**Comment by Joe0708** [comment]
@LeoMobileDeveloper 
Thanks。Footer 问题已经解决了。
但是，
Header 刷新这个还是一样，iOS 10正常，但iOS 11 不行。
运行你的 Demo 却正常。

设置 isTranslucent 或 contentInsetAdjustmentBehavior 后刷新状态是正常的， 但是很多地方UI就会偏移了。
你可以通过这个项目看 [V2EX](https://github.com/Joe0708/V2EX)
在这个文件中 “UIScrollView+Refresh.swift” 修改
