### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by ZClee128** [LeoMobileDeveloper/PullToRefreshKit#27]
添加上拉刷新没添加成功

**Comment by LeoMobileDeveloper** [comment]
怎么添加的？版本多少？

**Comment by ZClee128** [comment]
0.8.2，就是按照你的文档添加的默认的

**Comment by ZClee128** [comment]
0.0.2

**Comment by LeoMobileDeveloper** [comment]
能提供更详细的代码信息么？无法复现你说的问题，我的步骤：

1. 新建一个项目
2. CocoaPod安装PullToRefreshKit,0.8.2版本
3. 新建一个TableView：

```
        let tableView = UITableView(frame: view.bounds)
        tableView.dataSource = self
        view.addSubview(tableView)
        tableView.configRefreshFooter(with: DefaultRefreshFooter()) {
            
        };
```

**Comment by ZClee128** [comment]
self.tableView.configRefreshHeader(with: DefaultRefreshHeader.header()) {
            self.page = 1
            self.isUp = true
            self.loadListUrl()
            self.loadUrl()
        }
        
        self.tableView.configRefreshFooter(with: DefaultRefreshFooter.footer()) {
            self.isUp = false
            self.page += 1
            self.loadListUrl()
        }
我是这样添加的，头部成功了，尾部不行

**Comment by ZClee128** [comment]
我知道了，我把它移除了，怎么设置加载完消失

**Comment by LeoMobileDeveloper** [comment]
在加载完毕的闭包调：

```
self.tableView.switchRefreshFooter(to: .removed)
```
