### ISSUE TITLE
能不能实现下面的这几个效果？

### ISSUE THREAD

**Issue by Sabirjan** [LeoMobileDeveloper/PullToRefreshKit#29]
https://github.com/scwang90/SmartRefreshLayout/raw/master/art/gif_Material.gif

https://github.com/scwang90/SmartRefreshLayout/raw/master/art/gif_practive_weibo.gif

谢谢，我这里网速比较慢，没法上传图片了

**Comment by LeoMobileDeveloper** [comment]
@Sabirjan 第一个实现不了，原理上不一致，第二个应该可以实现

**Comment by Sabirjan** [comment]
第二个怎么实现，能不能简单的代码贴一下，我把优酷的改不行。

**Comment by Sabirjan** [comment]
@LeoMobileDeveloper 有时间帮个忙，谢谢
