### ISSUE TITLE
请教大神

### ISSUE THREAD

**Issue by tosslife** [LeoMobileDeveloper/PullToRefreshKit#3]
请教大神，左滑 横向collectionview 刷新提示文字和图片 不在collectionview 高度的正中间 该怎么修复这个高度呢？ 
我在pulltorefresh 225行 设置height: self.frame.height / 2  但是并不能完美的居中 还是偏上
请问怎样能完美的解决呢？

**Comment by LeoMobileDeveloper** [comment]
@tosslife 可以上个截图吗？不是很清楚具体的状况

**Comment by tosslife** [comment]
![ad6bc439-4ad6-43ca-a15a-88bc5f85ab28](https://cloud.githubusercontent.com/assets/7598390/21757754/54212948-d66e-11e6-856d-17efabac3781.png)

![30227e54-7c81-450a-8c73-5ef1de68fc5c](https://cloud.githubusercontent.com/assets/7598390/21757748/4e4f87d0-d66e-11e6-8507-5b761e9e3a50.png)

**Comment by LeoMobileDeveloper** [comment]
@tosslife 你这个看起来像是 collectionView的frame过大了，就是高度过高，文字的中心在高度的一半。建议log下frame或者用UI debugging看看高度对不对。
