### ISSUE TITLE
How to trigger the loading without dragging?

### ISSUE THREAD

**Issue by JunsW** [LeoMobileDeveloper/PullToRefreshKit#32]
怎么不拖动触发刷新?

**Comment by LeoMobileDeveloper** [comment]
```
self.tableView.switchRefreshHeader(to: .refreshing)
```

Demo里有例子：[源文件](https://github.com/LeoMobileDeveloper/PullToRefreshKit/blob/master/Demo/Demo/DefaultTableViewController.swift)
