### ISSUE TITLE
xcode9.3+swift4.1上出现大量这样的错误，但程序却能正常运行

### ISSUE THREAD

**Issue by zzzzzzzzzy** [LeoMobileDeveloper/PullToRefreshKit#34]
Friend.storyboard: error: IB Designables: Failed to render and update auto layout status for FriendRequestViewController (WEa-Aa-6Nn): dlopen(PullToRefreshKit.framework, 1): no suitable image found.  Did find:
	PullToRefreshKit.framework: required code signature missing for 'PullToRefreshKit.framework'

没升级xcode前完全正常，现在看不懂了，完全找不到错误在哪，麻烦大神帮忙看看，谢谢。

**Comment by LeoMobileDeveloper** [comment]
CocoaPod 升级到1.5.0应该就好了，我本地环境是XCode9.3+swfit4.1+CocoaPod 1.5.0，没有复现这个问题

```
sudo gem install cocoapods
```
