### ISSUE TITLE
Footer at top when empty data

### ISSUE THREAD

**Issue by sbhmajd** [LeoMobileDeveloper/PullToRefreshKit#36]
Thank you for great work,

I have small issue if you could help me please?

![simulator screen shot - iphone 8 - 2018-04-15 at 12 46 41](https://user-images.githubusercontent.com/23249321/38777115-26655a94-40ab-11e8-8c42-7201f096f6e1.png)

As you can see when number of items is ZERO ( empty ) ,, footer goes up at top

![simulator screen shot - iphone 8 - 2018-04-15 at 12 48 05](https://user-images.githubusercontent.com/23249321/38777121-41154dfe-40ab-11e8-9350-4b6a6edd6938.png)

Any idea how to keep it at bottom? ( like header at top )

**Comment by sbhmajd** [comment]
PullToRefreshKit (0.8.2)

CollectionView Demo Example

Just return 0 items in numberOfItemsInSection

**Comment by LeoMobileDeveloper** [comment]
You may remove footer when number of items is zero，footer is at then bottom of last cell. Currently, it does not support footer to be at the bottom of TableView

**Comment by sbhmajd** [comment]
Yes that will work when empty, but i just thought how about 1 item xD?

Look like this, i'm trying to figure out how this is working,
If we can change frame of footer to be at bottom,, is that hard?

Thanks for your help

![simulator screen shot - iphone 8 - 2018-04-15 at 13 00 43](https://user-images.githubusercontent.com/23249321/38777240-495f27da-40ad-11e8-80ce-124281c753db.png)

**Comment by sbhmajd** [comment]
Solved it,,

Inside Footer.swift

change handleContentSizeChange from

`func handleContentSizeChange(_ change: [NSKeyValueChangeKey : Any]?){
        self.frame = CGRect(x: 0,y: self.attachedScrollView.contentSize.height,width: self.frame.size.width,height: self.frame.size.height)
    }`

To

`func handleContentSizeChange(_ change: [NSKeyValueChangeKey : Any]?){
        self.frame = CGRect(x: 0,y: max(self.attachedScrollView.frame.height, self.attachedScrollView.contentSize.height) ,width: self.frame.size.width,height: self.frame.size.height)
    }`
 
How i can do this change for Pod, sorry i'm new with github things,, should i do fork and fix it?
Then how i can use it after that?

Thanks again @LeoMobileDeveloper
