### ISSUE TITLE
Could you provide a method to tint the Refresh View?

### ISSUE THREAD

**Issue by dymx101** [LeoMobileDeveloper/PullToRefreshKit#4]
Hi Leo,
@LeoMobileDeveloper Now both the header or the footer are in **black**, so it's looks bad on dark background, could you provide a method (sth. like `setThemeColor:`) to change all the colors of the text and image all-in-one?

Thanks!

**Comment by dymx101** [comment]
Or if you could accept a PR, I can add this feature for you 👍

**Comment by LeoMobileDeveloper** [comment]
@dymx101 Good idea. Thanks

**Comment by dymx101** [comment]
You're welcome XD
