### ISSUE TITLE
更新

### ISSUE THREAD

**Issue by chenjianyong** [LeoMobileDeveloper/PullToRefreshKit#43]
能否更新到swift4.2版本

**Comment by LeoMobileDeveloper** [comment]
暂时没时间，估计国庆节假期会修复一波Bug，然后更新到Swift4.2

**Comment by FormioCour** [comment]
+1

**Comment by LeoMobileDeveloper** [comment]
已更新

**Comment by FormioCour** [comment]
<img width="326" alt="wx20181007-075234 2x" src="https://user-images.githubusercontent.com/36736095/46576811-2a1da300-ca06-11e8-86a9-d2bd8954a1bb.png">

仍然有问题，没能兼容Swift 4.2，环境：`Xcode10`，`Swift 4.2`，`PullToRefreshKit (0.8.7)`

**Comment by LeoMobileDeveloper** [comment]
@FormioCour  Sorry，昨天忘记改swift version，以为XCode 10默认就是swift 4.2。这次应该可以了，尝试下0.8.8，如果还有问题再反馈给我
