### ISSUE TITLE
我想在下拉刷新header上面再加一个空白，可以实现么

### ISSUE THREAD

**Issue by nirvana72** [LeoMobileDeveloper/PullToRefreshKit#52]
由于特殊需求，想要在下拉刷新上面加一段空白，试过添加uicollectionview的header, 但是这个header 是在下拉刷新下面的， 有什么方法可以在RefreshableHeader 上面加一个view呢

**Comment by LeoMobileDeveloper** [comment]
可以看下Demo里的淘宝下拉刷新，写个自定义header就行了。

**Comment by nirvana72** [comment]
我的意思是想要在刷新上面加一个一直显示的view，或者把刷新header放在自定义headerview下面，这样我就有一个占位view在uicollectionview顶部，上层可以放一个随上下滑动渐隐渐出的banner或者搜索框什么的，不然banner会遮挡cell顶部内容
