### ISSUE TITLE
A lot of warning in xcode Version 8.3.3 , please update 

### ISSUE THREAD

**Issue by bizibizi** [LeoMobileDeveloper/PullToRefreshKit#8]
: 'M_PI' is deprecated: Please use 'Double.pi' or '.pi' to get the value of correct type and avoid casting.

**Comment by LeoMobileDeveloper** [comment]
These issue are fixed in version 0.5.0. Please try `pod repo update master` to update local pod cache. Then run `pod install`

**Comment by bizibizi** [comment]
last POD is 0 4 0, did you pushed your update ? it's not enough to push it to github
