### ISSUE TITLE
When I "pull" first time - image does not displays always

### ISSUE THREAD

**Issue by bizibizi** [LeoMobileDeveloper/PullToRefreshKit#9]
some bug, I use your code for declaration

**Comment by LeoMobileDeveloper** [comment]
Can you offer more details? Like iOS version, device model, system language?

**Comment by bizibizi** [comment]
xcode Version 8.3.3 , swift 3.x, iphone 5 ios 10.3.3, simulator

**Comment by bizibizi** [comment]
after update all was great
